name: netflixdb
services:
  #----------------------------------------------------------------------------
  # MySQL Container
  # https://hub.docker.com/_/mysql
  # Commands:
  #   mysql -u test -p netflixdb
  #----------------------------------------------------------------------------
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_DATABASE: netflixdb
    ports:
      - "3306:3306"

  #----------------------------------------------------------------------------
  # Oracle Container
  # https://container-registry.oracle.com/ords/ocr/ba/database/express
  # https://hub.docker.com/r/gvenzl/oracle-free (Apple M chips)
  # Commands:
  #   sqlplus -S / as sysdba @ /container-entrypoint-initdb.d/create_database.sql
  #----------------------------------------------------------------------------
  oracle:
    image: gvenzl/oracle-free:23-slim-faststart
    environment:
      ORACLE_PASSWORD: Test123
      APP_USER: netflixdb
      APP_USER_PASSWORD: netflixdb
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  #----------------------------------------------------------------------------
  # PostgreSQL Container
  # https://hub.docker.com/_/postgres
  # Commands:
  #   psql -U postgres postgres
  #----------------------------------------------------------------------------
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netflixdb
    ports:
      - "5432:5432"
