name: netflixdb
services:
  #----------------------------------------------------------------------------
  # MySQL Container
  # https://hub.docker.com/_/mysql
  # Commands:
  #   mysql -u test -p netflixdb
  #----------------------------------------------------------------------------
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_DATABASE: netflixdb
    ports:
      - "3306:3306"
#    volumes:
#      - ./build/artifacts/netflixdb-mysql.sql:/docker-entrypoint-initdb.d/netflixdb-mysql.sql

  #----------------------------------------------------------------------------
  # Oracle Container
  # https://container-registry.oracle.com/ords/ocr/ba/database/express
  # https://hub.docker.com/r/gvenzl/oracle-free (Apple M chips)
  # Commands:
  #   sqlplus -S / as sysdba @ /container-entrypoint-initdb.d/create_database.sql
  #----------------------------------------------------------------------------
  oracle:
    image: gvenzl/oracle-free:23-slim-faststart
    environment:
      ORACLE_PASSWORD: Test123
      APP_USER: netflixdb
      APP_USER_PASSWORD: netflixdb
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
#    volumes:
#      - ./build/artifacts/netflixdb-oracle.sql:/docker-entrypoint-initdb.d/netflixdb-oracle.sql
  #----------------------------------------------------------------------------
  # PostgreSQL Container
  # https://hub.docker.com/_/postgres
  # Commands:
  #   psql -U postgres postgres
  #----------------------------------------------------------------------------
  postgres:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netflixdb
    ports:
      - "5432:5432"
#    volumes:
#      - ./build/artifacts/netflixdb-postgresql.sql:/docker-entrypoint-initdb.d/netflixdb-postgresql.sql

  #----------------------------------------------------------------------------
  # SQL Server Container
  # https://hub.docker.com/_/microsoft-mssql-server
  # Commands:
  #   /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -d master -i /docker-entrypoint-initdb.d/create_database.sql
  #   /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -d Chinook
  #----------------------------------------------------------------------------
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Test123!
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    entrypoint: |
      bash -c '
      /opt/mssql/bin/sqlservr &
      sleep 15
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Test123! -C -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = '"'"'netflixdb'"'"') CREATE DATABASE [netflixdb];"
      wait
      '
#    volumes:
#      - ./build/artifacts/netflixdb-mssql.sql:/docker-entrypoint-initdb.d/netflixdb-mssql.sql
