spring.application.name: NetflixDB

spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:exchange_rates;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
  username: sa
  password:

spring.batch:
  jdbc:
    initialize-schema: always
  job:
    enabled: true
spring.h2.console:
  enabled: false
  path: /h2

spring.jpa:
  hibernate:
    ddlAuto: create
  properties:
    javax:
      persistence:
        schema-generation:
          scripts:
            action: create
            create-target: build/artifacts/netflixdb-h2.sql
    hibernate:
      show_sql: false
      format_sql: true
  generate-ddl: true
