spring.datasource:
  name: mysql
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/netflixdb
  username: mysql
  password: mysql

spring.jpa:
  properties:
    javax:
      persistence:
        schema-generation:
          scripts:
            create-target: build/artifacts/netflixdb-mysql.sql
