/** SQL dialect adapters for artifact export; see RepoExplainMds/05-service.md. */
package com.github.lerocha.netflixdb.service

import com.github.lerocha.netflixdb.entity.AbstractEntity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.ManyToMany
import jakarta.persistence.ManyToOne
import jakarta.persistence.OneToMany
import jakarta.persistence.OneToOne
import org.hibernate.boot.model.naming.Identifier
import org.hibernate.boot.model.naming.PhysicalNamingStrategy

/**
 * Dialect-specific SQL generation for schema export.
 * Uses reflection to map entity fields to INSERT column lists, skipping associations and generated ids.
 */
interface DatabaseStrategy {
    fun getPhysicalNamingStrategy(): PhysicalNamingStrategy

    fun getInitDatabase(): String = ""

    fun <T> getSqlValues(vararg properties: T): String

    fun <T : AbstractEntity> getInsertStatement(entity: T): String {
        val properties = getProperties(entity)
        val tableName = physicalTableName(entity)
        val names = properties.keys.joinToString(", ")
        val values = getSqlValues(*properties.values.toTypedArray())
        return "INSERT INTO $tableName ($names) VALUES ($values);"
    }

    fun <T : AbstractEntity> getInsertStatement(entities: List<T>): String {
        if (entities.isEmpty()) return ""
        if (entities.size == 1) return getInsertStatement(entities.first())

        // Multi-value INSERT; OracleStrategy overrides to emit one statement per row.
        val properties = getProperties(entities.first())
        val tableName = physicalTableName(entities.first())
        val names = properties.keys.joinToString(", ")
        return StringBuilder()
            .appendLine("INSERT INTO $tableName ($names) VALUES")
            .append(
                entities.joinToString(",\n") { entity ->
                    val values = getSqlValues(*getProperties(entity).values.toTypedArray())
                    "($values)"
                },
            )
            .appendLine(";")
            .appendLine()
            .toString()
    }

    /**
     * Builds a column name → value map from JPA field metadata and JavaBean getters.
     * [ManyToOne] / [OneToOne] associations are exported as foreign-key id columns.
     */
    fun <T : AbstractEntity> getProperties(entity: T): Map<String, Any?> {
        val getterValues =
            (entity.javaClass.superclass.declaredMethods + entity.javaClass.declaredMethods)
                .filter { it.name.startsWith("get") }
                .associate { it.name.lowercase() to it.invoke(entity) }

        return (entity.javaClass.superclass.declaredFields.toList() + entity.javaClass.declaredFields.toList())
            .filter { field -> field.annotations.none { it.annotationClass.java in ignorePropertyAnnotations } }
            .filter { field -> getterValues.containsKey("get${field.name.lowercase()}") }
            .associate { field ->
                val isForeignKey = field.annotations.any { it.annotationClass.java in foreignKeyAnnotations }
                val columnStem = if (isForeignKey) "${field.name}Id" else field.name
                val columnName =
                    getPhysicalNamingStrategy()
                        .toPhysicalColumnName(Identifier(columnStem, false), null)
                        .text
                columnName to getterValues["get${field.name.lowercase()}"]
            }
    }

    private fun <T : AbstractEntity> physicalTableName(entity: T): String =
        getPhysicalNamingStrategy()
            .toPhysicalTableName(Identifier(entity.javaClass.simpleName, false), null)
            .text

    companion object {
        // Collections are not scalar columns; id is generated by the database on import.
        val ignorePropertyAnnotations = setOf(OneToMany::class.java, ManyToMany::class.java, GeneratedValue::class.java)
        val foreignKeyAnnotations = setOf(OneToOne::class.java, ManyToOne::class.java)
    }
}
