package com.github.lerocha.netflixdb.service

import com.github.lerocha.netflixdb.entity.Episode
import com.github.lerocha.netflixdb.entity.Movie
import com.github.lerocha.netflixdb.entity.Season
import com.github.lerocha.netflixdb.entity.TvShow
import com.github.lerocha.netflixdb.entity.ViewSummary
import com.github.lerocha.netflixdb.repository.MovieRepository
import com.github.lerocha.netflixdb.repository.SeasonRepository
import com.github.lerocha.netflixdb.repository.TvShowRepository
import com.github.lerocha.netflixdb.repository.ViewSummaryRepository
import org.hibernate.boot.MetadataSources
import org.hibernate.boot.registry.StandardServiceRegistryBuilder
import org.hibernate.tool.hbm2ddl.SchemaExport
import org.hibernate.tool.schema.TargetType
import org.slf4j.LoggerFactory
import org.springframework.boot.autoconfigure.jdbc.DataSourceProperties
import org.springframework.stereotype.Service
import java.io.File
import java.time.OffsetDateTime
import java.util.EnumSet

@Service
class DatabaseExportService(
    private val dataSourceProperties: DataSourceProperties,
    private val databaseStrategyFactory: DatabaseStrategyFactory,
    private val movieRepository: MovieRepository,
    private val tvShowRepository: TvShowRepository,
    private val seasonRepository: SeasonRepository,
    private val viewSummaryRepository: ViewSummaryRepository,
) {
    private val logger = LoggerFactory.getLogger(javaClass)

    companion object {
        const val CHUNK_SIZE = 100
    }

    fun exportSchema(
        databaseName: String,
        filename: String,
    ) {
        val path = "build/artifacts/$filename"
        File(path).parentFile.mkdirs()
        val settings =
            mutableMapOf<String, Any>(
                "connection.driver_class" to dataSourceProperties.driverClassName,
                "hibernate.connection.url" to dataSourceProperties.url,
                "hibernate.connection.username" to dataSourceProperties.username,
                "hibernate.connection.password" to dataSourceProperties.password,
                "hibernate.hbm2ddl.auto" to "create",
                "show_sql" to "true",
                "hibernate.implicit_naming_strategy" to "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy",
                "hibernate.physical_naming_strategy" to "org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy",
            )

        val metadata =
            MetadataSources(
                StandardServiceRegistryBuilder()
                    .applySettings(settings)
                    .build(),
            ).addAnnotatedClasses(Movie::class.java)
                .addAnnotatedClasses(TvShow::class.java)
                .addAnnotatedClasses(Season::class.java)
                .addAnnotatedClasses(Episode::class.java)
                .addAnnotatedClasses(ViewSummary::class.java)
                .buildMetadata()

        File(path).writeText(
            """
            /**********************************************************************************
              NetflixDB for ${databaseName.uppercase()}
              Description: Creates and populates the Netflix database.
              Created on: ${OffsetDateTime.now()}
              Author: Luis Rocha
               
              WARNING: This file was generated by a tool and changes to this file will be lost
                       when this file is regenerated.
            ***********************************************************************************/
            ${databaseStrategyFactory.getInstance(databaseName).getInitDatabase()}
            """.trimIndent(),
        )

        SchemaExport()
            .setHaltOnError(true)
            .setFormat(true)
            .setDelimiter(";")
            .setOutputFile(path)
            .execute(EnumSet.of(TargetType.SCRIPT), SchemaExport.Action.CREATE, metadata)

        logger.info("Exported schema for $databaseName to $path")
    }

    fun exportData(
        databaseName: String,
        filename: String,
    ) {
        val databaseStrategy = databaseStrategyFactory.getInstance(databaseName)
        val stringBuilder = StringBuilder()

        stringBuilder.appendLine().appendLine(printHeader("Movies data"))
        movieRepository.findAll().chunked(CHUNK_SIZE).forEach { chunk ->
            stringBuilder.appendLine(databaseStrategy.getInsertStatement(chunk))
        }

        stringBuilder.appendLine().appendLine(printHeader("TV Show data"))
        tvShowRepository.findAll().chunked(CHUNK_SIZE).forEach { chunk ->
            stringBuilder.appendLine(databaseStrategy.getInsertStatement(chunk))
        }

        stringBuilder.appendLine().appendLine(printHeader("Season data"))
        seasonRepository.findAll().chunked(CHUNK_SIZE).forEach { chunk ->
            stringBuilder.appendLine(databaseStrategy.getInsertStatement(chunk))
        }

        stringBuilder.appendLine().appendLine(printHeader("ViewSummary data"))
        viewSummaryRepository.findAll().chunked(CHUNK_SIZE).forEach { chunk ->
            stringBuilder.appendLine(databaseStrategy.getInsertStatement(chunk))
        }

        val path = "build/$filename"
        File(path).appendText(stringBuilder.toString())
        logger.info("Exported data for $databaseName to $path")
    }

    private fun printHeader(text: String) =
        """
        /**********************************************************************************
          $text
        ***********************************************************************************/
        """.trimIndent()
}
